name: TV check

on:
  schedule:
    - cron: "35 2 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  run_tv_detection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Download FFprobe
      run: |
        mkdir ffprobe
        wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
        tar xvf ffmpeg-git-*-static.tar.xz && rm -rf ffmpeg-git-*-static.tar.xz
        mv ffmpeg-git-*/ffmpeg  ffmpeg-git-*/ffprobe /usr/bin/
        #curl -L -o ffprobe/ffprobe https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/ffmpeg/7:6.1.1-1ubuntu1/ffmpeg_6.1.1.orig.tar.xz
        #tar -xJf ffprobe/ffprobe -C ffprobe/
        #chmod +x ffprobe/ffprobe
        #sudo mv ffprobe/ffprobe /usr/local/bin/  # 将FFprobe移动到系统路径
        
    - name: Debug info
      run: |
        pwd
        ls -la
        ffprobe -version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 如果有依赖需求，请将其添加到 requirements.txt 文件中

    - name: Run TV Ckeck
      run: python ${{ github.workspace }}/check_iptv.py  # 替换为你的Python文件的名称
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: iptv-all
        path: ${{ github.workspace }}/

    - name: 提交更改
      run: |
        git config --local user.email "pantong1995@126.com"
        git config --local user.name "xiaotong1995"
        git add .
        git commit *.txt -m "Add generated file"
        #git pull --rebase
        git push -f
